FROM node:22.13.0-slim AS frontend-build
WORKDIR /app/adminPanel/admin-frontend
COPY adminPanel/admin-frontend/package*.json ./
RUN npm install
COPY adminPanel/admin-frontend/ ./
RUN npm run build

FROM python:3.13-slim
WORKDIR /app
COPY requirements.txt ./
RUN pip install -r requirements.txt
COPY . .
COPY --from=frontend-build /app/adminPanel/admin-frontend/dist ./adminPanel/admin-frontend/dist

EXPOSE 8000
# Remove the brackets and sh -c wrapper entirely
CMD sh -c "uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000}"
